#!/usr/bin/env python

# Filename: kdb
# Module:   kdb
# Date:     04th August 2004
# Author:   James Mills <prologic@shortcircuit.net.au>

"""kdb

ShortCircuit Knowledge (IRC) Bot
"""

#Python Modules
import sys, traceback

#My Modules
from daemonize import daemonize
import utils, CmdOpt

#Program Modules
import conf, data
import Bot

#Set command-line options
short = 'hd'
long = ['--help', '--daemon']

usage = "\
Usage: [options] ' + utils.getProgName() + ':\n\
       -h, --help     (Display this help)\n\
       -d, --daemon   (Daemon mode)\n"

def main():
	utils.writePID(conf.paths["logs"])

	data.load()

	try:

		bot = Bot.Bot()

		while bot.running:

			for server, port in conf.servers:
				print "Connecting to server: " + server + " on port: " + str(port)
				bot.ircSERVER(server, port)

				if bot.connected:
					bot.ircUSER(conf.me["user"], "localhost", server, conf.me["name"])
					bot.ircNICK(conf.me["nick"])
					for channel in conf.channels:
						bot.ircJOIN(channel)

				while bot.connected:
					bot.process()

	except Exception, e:
		print "ERROR: " + str(e)
		print "\nTraceBack follows:\n"
		traceback.print_exc()

	data.save()

if __name__ == "__main__":
	cmdopt = CmdOpt.CmdOpt(short, long, usage, True)

	options = cmdopt.options()
	args = cmdopt.args

	if options.has(['-h', '--help']):
		print usage
		sys.exit(0)
	elif options.has(['-d', '--daemon']):
		logfile = conf.paths["logs"] + "/" + utils.getProgName() + '.log'
		daemonize('/dev/null', logfile, logfile)
	main()

#vim: tabstop=3 nocindent autoindent
