#!/usr/bin/env python

import os
import sys
import pydoc

def processPackage(package):

	pydoc.writedoc(package)

	path = package.replace(".", "/")
	for file in os.listdir(path):

		if os.path.isfile("%s/%s" % (path, file)):

			(root, ext) = os.path.splitext(file)

			if not root == "__init__":
				if ext == ".py":
					module = "%s.%s" % (package, root)
					pydoc.writedoc(module)
		else:
			if not file in [".svn", "CVS"]:
				processPackage("%s.%s" % (package, file))
	
def main():
	package = "kdb"
	docsDir = "docs/%s" % package
	sys.path.append(package)
	processPackage(package)
	os.system("mv *.html %s" % docsDir)
	if not os.path.isfile("%s/index.html" % docsDir):
		os.symlink("%s.html" % package, "%s/index.html" % docsDir)

if __name__ == "__main__":
	main()
